worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format loki_json escape=json '{'
            '"time": "$time_iso8601",'
            '"remote_addr": "$remote_addr",'
            '"client_ip": "$http_x_forwarded_for",'
            '"request": "$request",'
            '"status": "$status",'
            '"body_bytes_sent": "$body_bytes_sent",'
            '"http_referer": "$http_referer",'
            '"http_user_agent": "$http_user_agent",'
            '"host": "$host"'
            '}';

    include /etc/nginx/conf.d/*.conf;
}
