server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /positions/positions.yaml

scrape_configs:
  - job_name: restobite-caddy-public-info
    static_configs:
      - targets:
          - localhost
        labels:
          env: production
          level: info
          source: restobite-caddy
          __path__: /var/log/caddy/restobite_public_access.json
  - job_name: restobite-caddy-public-error
    static_configs:
      - targets:
          - localhost
        labels:
          env: production
          level: error
          source: restobite-caddy
          __path__: /var/log/caddy/restobite_public_error.json
